name: 'doc-flow'

services:
  app:
    container_name: doc-flow-backend
    image: node:20.18-bullseye-slim
    ports: 
      - "3000:3000"
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - network-doc-flow
    command: npm run start

  postgres:
    container_name: doc-flow-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network-doc-flow

  adminer:
    container_name: doc-flow-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - network-doc-flow

  migrate:
    container_name: doc-flow-migrate
    image: node:20.18-bullseye-slim
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - network-doc-flow
    command: [ 
      "npm",
      "run",
      "migrate:up"
    ]

networks:
  network-doc-flow:
    driver: bridge

volumes:
  pgdata:
