export enum Role {
  VIEW_ANY = 'VIEW_ANY',
  VIEW_OWN = 'VIEW_OWN',
  CREATE_ANY = 'CREATE_ANY',
  CREATE_USER = 'CREATE_USER',
  UPDATE_ANY = 'UPDATE_ANY',
  UPDATE_OWN = 'UPDATE_OWN',
  DELETE_ANY = 'DELETE_ANY',
  DELETE_OWN = 'DELETE_OWN',
}
